defaults:
  - v32
  - _self_

compile: true          # PyTorch 2.0 optimization
mixed_precision: 'bf16'         # Enable mixed precision (no/fp16/bf16)
enable_lora: true              # Use LoRA for finetuning

pretrained_path: "OliBomby/Mapperatorinator-v32"     # Path to pretrained model weights
pretrained_gamemode: 0  # Only load weights for the specified gamemode from a multi-gamemode checkpoint

data:                  # Data settings
  dataset_type: "mmrs"
  train_dataset_path: "/workspace/datasets/Voxell"
  test_dataset_path: "/workspace/datasets/Voxell"
  train_dataset_start: 0
  train_dataset_end: 10
  test_dataset_start: 0
  test_dataset_end: 0
  gamemodes: [0]
  ranked_statuses: [-2, -1, 0, 1, 2, 3, 4]  # List of ranked statuses to include in the dataset (-2 = graveyard, -1 = wip, 0 = pending, 1 = ranked, 2 = approved, 3 = qualified, 4 = loved)
  min_year: null  # Must be null if you want to include unranked maps
  max_year: null

dataloader:             # Dataloader settings
  num_workers: 1
  drop_last: false
  balancer_buffer_size: 0

optim:                  # Optimizer settings
  name: muon
  base_lr: 0.0004         # Should be scaled with the number of devices present
  base_lr_2: 0.0001        # Secondary learning rate for the internal optimizer
  batch_size: 32
  grad_acc: 16
  total_steps: 1000
  warmup_steps: 0
  sustain_steps: 0      # Steps to sustain the learning rate after warmup
  weight_decay: 0.01
  lr_scheduler: cosine
  final_cosine: 0

lora:
  r: 64
  lora_alpha: 128
  target_modules: ['Wq', 'Wkv', 'Wqkv', 'Wo']
  lora_dropout: 0.05
  bias: "none"
  init_lora_weights: "pissa"

lora_metadata:
  ckpt_subfolders: ["gamemode=0"]  # Only apply this LoRA when inference loads the gamemode=0 checkpoint subfolder.

